# Generated by Django 5.2.4 on 2025-07-16 18:18

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Пользователь с таким email уже существует."},
                max_length=255,
                unique=True,
                verbose_name="Электронная почта",
            ),
        ),
    ]
