# Generated by Django 5.2.4 on 2025-07-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Если отмечено, товар будет отображаться на сайте",
                verbose_name="Опубликовано",
            ),
        ),
    ]
